### ISSUE TITLE
Error while installing Windows 7

### ISSUE THREAD

**Issue by Andrei-Vakulski** [nitaliano/react-native-mapbox-gl#250] opened 2016-01-19 14:41 UTC
Hello, got this error trying to install it on windows 7

> ./scripts/download-mapbox-gl-native-ios.sh 3.0.0

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\Program Files (x86)\nodejs\node.exe" "c:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "react-native-mapbox-g
l" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! react-native-mapbox-gl@3.1.1 preinstall: `./scripts/download-mapbox-gl-native-ios.sh 3.0.0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-mapbox-gl@3.1.1 preinstall script './scripts/download-mapbox-gl-native-ios.sh 3.0.0'.
npm ERR! This is most likely a problem with the react-native-mapbox-gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/download-mapbox-gl-native-ios.sh 3.0.0
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native-mapbox-gl
npm ERR! There is likely additional logging output above.

**Comment by bsudekum** [comment] 2016-01-19 17:33
dupe of https://github.com/mapbox/react-native-mapbox-gl/issues/170

**Closed as completed by bsudekum** 2016-01-19 17:33 UTC
