### ISSUE TITLE
[v6]  Trying to remove a view index above child count 4 view tag

### ISSUE THREAD

**Issue by butchmarshall** [nitaliano/react-native-mapbox-gl#773] opened 2017-11-17 03:34 UTC
I'm running v6 master branch right now.

1) I long-press a line, which causes the MapboxGL_TrailInformation to properly render a line
2) I then clear the line, which causes MapboxGL_TrailInformation to render null.

This is when I get the crash at the bottom.

Main render block:
```
    <MapboxGL.MapView>
	<MapboxGL_Trails />
	<MapboxGL_Places />
	<MapboxGL_TrailInformation />
    </MapboxGL.MapView>

```

MapboxGL_TrailInformation render block:

```
class MapboxGL_TrailInformation extends React.Component {
	constructor(props) {
		super(props);
	}
	shouldComponentUpdate(nextProps, nextState) {
		if (nextProps.trail_information != this.props.trail_information) {
			return true;
		}
		return false;
	}
	render() {
		if (!this.props.trail_information.line) {
			return null;
		}
		const shapeGeoJson = makeLineString(this.props.trail_information.line.points);

		return (
			<MapboxGL.ShapeSource key={"trail_information_source"} id={"trail_information_source"} shape={shapeGeoJson}>
				<MapboxGL.LineLayer
					id={"trail_information"}
					style={layerStyles.line} />
			</MapboxGL.ShapeSource>
		);
	}
}
```

![image](https://user-images.githubusercontent.com/339763/32927990-bfb77438-cb1d-11e7-8497-76c995e5efe0.png)

**Comment by butchmarshall** [comment] 2017-11-17 03:44
This is a workaround for anyone else encountering this - don't remove the ShapeSource, only the line.

```
class MapboxGL_TrailInformation extends React.Component {
	constructor(props) {
		super(props);
	}
	shouldComponentUpdate(nextProps, nextState) {
		return true;
		if (nextProps.trail_information != this.props.trail_information) {
			return true;
		}
		return false;
	}

	render() {
		const shapeGeoJson = ((!this.props.trail_information.line)? {} : makeLineString(this.props.trail_information.line.points));

		return (
			<MapboxGL.ShapeSource key={"trail_information_source"} id={"trail_information_source"} shape={shapeGeoJson}>
				{(() => {
					if (this.props.trail_information.line) {
						return (
							<MapboxGL.LineLayer
								id={"trail_information"}
								style={layerStyles.line} />
						);
					}
				})()}
			</MapboxGL.ShapeSource>
		);
	}
}
```

**Comment by nitaliano** [comment] 2017-11-17 19:33
are you still seeing this on `master`?

**Comment by butchmarshall** [comment] 2017-11-18 04:11
Just pulled latest master - fixed!

**Comment by alfonsodev** [comment] 2017-12-07 18:11
I'm having this issue too, will be master be published in `npm` soon?

**Comment by nitaliano** [comment] 2017-12-07 18:22
Yea, I'll make a rc publish tomorrow

**Comment by Jose4gg** [comment] 2017-12-08 14:06
Is still happens on master for me...

**Comment by Jose4gg** [comment] 2017-12-08 15:37
If I add a ShapeSource to the Map and I try to delete it without moving the map, it gives me the same error on master @nitaliano

**Comment by nitaliano** [comment] 2017-12-08 17:20
Reopened I'll try to reproduce this today

**Comment by Emilios1995** [comment] 2017-12-08 17:58
This also happens for me when I render a line that follows the coordinates of some Annotations and start deleting them.
I wasn't able to notice when and why it happens. I just randomly create and delete annotations and eventually it crashes.
Here's the code I use for the line
```js
{this.state.points.length > 1 && (
            <MapboxGL.ShapeSource
              id="routeSource"
              shape={lineString(this.state.points)}
            >
              <MapboxGL.LineLayer
                id="routeFill"
                style={layerStyles.route}
                belowLayerID="originInnerCircle"
              />
            </MapboxGL.ShapeSource>
          )}
```

**Comment by nitaliano** [comment] 2017-12-08 18:23
@Jose4gg and @Emilios1995 I haven't been able to reproduce the crash at all. Here is the gist that I'm using it's `CustomIcon.js` from the example app. I'm on this PR https://github.com/mapbox/react-native-mapbox-gl/pull/852 which is just a few commits ahead of master

https://gist.github.com/nitaliano/4e46d130b7163b2d1778067746f76dbf

I also tried rendering a source with some layers on the map and setting a settimeout to remove the source and it doesn't produce a crash

**Comment by Emilios1995** [comment] 2017-12-08 18:48
@nitaliano Sorry, I know this is hard to reproduce. I recorded my screen while it happened. Here's the [video](https://drive.google.com/file/d/0B-veAm3gOE-WektPV3I5UkdaWEFkQk0wbWk4WWNNRG1jbVBV/view?usp=sharing)
Let's see if you manage to notice the cause.
Here's the full code: https://gist.github.com/Emilios1995/99c35c38eda3aec87913b18b65fef769

Also, as you may notice, sometimes the callout doesn't dissapear after removing the annotation,  but that's a different issue.

**Comment by nitaliano** [comment] 2017-12-08 21:29
It appears to be related to the legacy annotation views and not sources/layers. I was able to reproduce it switching my example to using annotation views instead of a symbol layer. Will look into fixes for them

@alfonsodev just published `6.0.2-rc1`

**Comment by nitaliano** [comment] 2017-12-08 23:51
@Emilios1995 I figured it out I'll have a PR for you soon that fixes this issue and the Callouts not removing. Your code samples are really helpful!

**Comment by bcalik** [comment] 2017-12-10 10:21
I have the same issue. My render methods are below.
`master` and `6.0.2-rc1` doesn't work at all for me, so I try on `6.0.1`.
I also applied this (https://github.com/mapbox/react-native-mapbox-gl/commit/5f252c7657c8df5a07d94acff4e666d3285d3435) commit on `6.0.1`

Basicly what I do is, I manually generate clusters using Supercluster.
Then render markers as `PointAnnotation`, and clusters as `ShapeSource`/`CircleLayer`.

```javascript
renderMarker(data) {
    if (this.state.activeDataIndex !== null) {
      return null;
    }

    return (
      <MapboxGL.PointAnnotation
        id={`marker-${data.id}`}
        key={data.id}
        selected={false}
        coordinate={[
          parseFloat(data.cihaz.longitude),
          parseFloat(data.cihaz.latitude),
        ]}
        onSelected={() => this.showActiveDataPanel(this.getIndexFromGpsId(data.id))}
        anchor={{ x: 0.5, y: 1 }}
      >
        <GpsMarker data={data} />
      </MapboxGL.PointAnnotation>
    )
  },

  renderClusters() {
    let clusters = {
      type: 'FeatureCollection',
      features: []
    };
    this.state.clusteredData.map((item) => {
      if (item.properties.point_count > 0) {
        clusters.features.push(item);
      }
    });

    return (
      <MapboxGL.ShapeSource
        id='clusters'
        shape={clusters}
      >
        <MapboxGL.SymbolLayer
          id='pointCount'
          style={layerStyles.clusterCount}
        />
        <MapboxGL.CircleLayer
          id='clusteredPoints'
          belowLayerID='pointCount'
          filter={['has', 'point_count']}
          style={layerStyles.clusteredPoints}
        />
      </MapboxGL.ShapeSource>
    );
  },

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'white' }}>
        <Toolbar
          titleLabel="Araç Takip"
          leftChildren={[
            {
              icon: 'angle-left',
              action: () => app.getMasterLayout().popScene(),
            },
          ]}
        />
        <Ready>
          <MapboxGL.MapView
            style={{ flex: 1 }}
            styleURL={this.state.styleURL}
            ref={(c) => { this.map = c; }}
            centerCoordinate={[this.initialPoint.longitude, this.initialPoint.latitude]}
            zoomLevel={this.initialPoint.zoomLevel}
            onLayout={() => this.onMapLayout()}
            onPress={() => this.hideMapOptionsPanel()}
            onRegionDidChange={regionFeature => this.onRegionDidChange(regionFeature)}
          >
            {this.renderClusters()}
            {
              this.state.clusteredData.map((item) => {
                if (item.properties.point_count === 0) {
                  return this.renderMarker(item.properties.data);
                }
              })
            }
          </MapboxGL.MapView>
          {this.renderMapOptionsPanel()}
          {this.renderMapButtons()}
          {this.renderActiveDataPanel()}
        </Ready>
      </View>
    );
  },
});
```

**Comment by nitaliano** [comment] 2017-12-11 04:15
I just added more commits to https://github.com/mapbox/react-native-mapbox-gl/pull/852 that should fix the Callout not being deleted and `Trying to remove a view index above child count n view tag`. The callout issue was a side effect of the same issue as the remove a view bug.

**Comment by nitaliano** [comment] 2017-12-11 22:55
Closing this out fix has been merged into master

**Closed as completed by nitaliano** 2017-12-11 22:55 UTC

**Comment by Emilios1995** [comment] 2017-12-11 23:29
@nitaliano Thank you! I can confirm it works perfectly now.
