### ISSUE TITLE
Random crashes with custom png SymbolLayer marker

### ISSUE THREAD

**Issue by mtt87** [nitaliano/react-native-mapbox-gl#920] opened 2018-01-01 22:25 UTC
Currently testing only on iOS I see many random crashes in the app when there is a Map component using `ShapeSource` and `SymbolLayer` with a custom `.png`
```js
const markerBlack = require('../../images/pin_nero.png');

const layerStyles = MapboxGL.StyleSheet.create({
  icon: {
    iconImage: markerBlack,
    iconAllowOverlap: true,
    iconIgnorePlacement: true,
    iconSize: Platform.OS === 'android' ? 1 : 0.5,
  },
});

<MapboxGL.ShapeSource
  id="restaurant"
  shape={{
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [lng, lat],
        },
        id: 1,
      },
    ],
  }}
>
  <MapboxGL.SymbolLayer id="singlePoint" style={layerStyles.icon} />
</MapboxGL.ShapeSource>;

```
It's definitely in the native code because the app is totally crashing (no RN red screen with the stack trace, no chrome debug stack trace), I'm not very proficient with native code and Xcode, this is what I can see
`Mapbox`___lldb_unnamed_symbol8632$$Mapbox:`
<img width="1128" alt="screen shot 2018-01-01 at 23 20 14" src="https://user-images.githubusercontent.com/2150927/34471457-aa0a57bc-ef4a-11e7-81e1-d625b9b10e0b.png">

**Comment by mtt87** [comment] 2018-01-02 22:35
With https://github.com/mapbox/react-native-mapbox-gl/issues/918#issuecomment-354847711

Seems like it's not crashing anymore 👍 

I'll do a bit more testing tomorrow and if there are no more crashes I'll close this issue 😄  thanks!

**Comment by nitaliano** [comment] 2018-01-02 22:37
@mtt87 just made a PR for it https://github.com/mapbox/react-native-mapbox-gl/pull/922

**Comment by jsaguiar** [comment] 2018-01-03 11:52
It seams to be fixed! thanks @mtt87

**Comment by EricPKerr** [comment] 2018-01-08 23:17
@nitaliano I am getting this error from the latest merged code in master.  It includes the merged https://github.com/mapbox/react-native-mapbox-gl/pull/922 PR:

```
Line 195:
[RCTMGLUtils fetchImage:_bridge url:styleValue.payload[@"value"] callback:^(NSError *error, UIImage *image) {
  if (image != nil) {
    dispatch_async(dispatch_get_main_queue(), ^{
      [_style setImage:image forName:styleValue.payload[@"value"]]; // Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
      [self setIconImage:layer withReactStyleValue:styleValue];
    });
  }
}];
```

This happens when the image is rendered before the map loads (unsure if it's related to the same main/background thread issue).  This appears to temporarily fix the issue but doesn't feel like the right solution:

```
<MapboxGL.MapView ...
onWillStartRenderingMap={() => this.setState({ready: true})}
>
{this.state.ready && this.renderMapChildren()}
<MapboxGL.MapView>
```

Stack Trace:

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000010b6881f8 in ___lldb_unnamed_symbol11750$$Mapbox ()
#1	0x000000010b4b1aa6 in ___lldb_unnamed_symbol4055$$Mapbox ()
#2	0x000000010a312a23 in __42-[RCTMGLStyle symbolLayer:withReactStyle:]_block_invoke_2 at /Users/ericpkerr/Code/MyApp/node_modules/@mapbox/react-native-mapbox-gl/ios/RCTMGL/RCTMGLStyle.m:198
#3	0x00000001127d02f7 in _dispatch_call_block_and_release ()
#4	0x00000001127d133d in _dispatch_client_callout ()
#5	0x00000001127dc5f9 in _dispatch_main_queue_callback_4CF ()
#6	0x000000010da36e39 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#7	0x000000010d9fb462 in __CFRunLoopRun ()
#8	0x000000010d9fa889 in CFRunLoopRunSpecific ()
#9	0x00000001164459c6 in GSEventRunModal ()
#10	0x00000001105895d6 in UIApplicationMain ()
#11	0x0000000109f4724f in main at /Users/ericpkerr/Code/MyApp/ios/MyApp/main.m:16
```

Would any other code help to reproduce this?

**Comment by nitaliano** [comment] 2018-01-08 23:30
@EricPKerr would you be able to throw together some code that would be able to reproduce the issue? I haven't run into any crashes since this PR, so some quick code would help me be able to debug it much faster.

**Comment by EricPKerr** [comment] 2018-01-10 01:14
@nitaliano It seems to happen when the map is loading and the map itself is added and removed from the view tree.  In my case this is from Redux prop changes.

You'd never have code like this with setTimeouts, but it causes similar re-renders as prop changes to the Component itself:

```
import marker from './assets/marker.png';

const styles = MapboxGL.StyleSheet.create({
  icon: {
    iconImage: marker,
    iconAllowOverlap: true,
    iconSize: 0.5,
  },
});

const POINT = [-73.970895, 40.723279];

class App extends React.Component {
  constructor (props) {
    super(props);

    this.state = {
      enabled: false
    };

    this.toggleEnabled = this.toggleEnabled.bind(this);
  }

  componentDidMount() {
    this.toggleEnabled(() => {
      this.toggleEnabled(() => {
        this.toggleEnabled(() => {
          this.toggleEnabled();
          //... etc
        })
      })
    })
  }

  toggleEnabled(next = () => {}) {
    this.setState({
      enabled: !this.state.enabled
    }, () => {
      setTimeout(next, 100);
    })
  }

  render() {
    if(!this.state.enabled) {
      return <View style={sheet.matchParent} />
    }

    return (
      <View style={sheet.matchParent}>
        <MapboxGL.MapView
          zoomLevel={9}
          ref={(c) => this._map = c}
          centerCoordinate={POINT}
          style={sheet.matchParent}>

          <MapboxGL.ShapeSource id='symbolLocationSource' shape={{
            "type": "Point",
            "coordinates": POINT
          }}>
            <MapboxGL.SymbolLayer
              id='symbolLocationSymbols'
              style={styles.icon}
            />
          </MapboxGL.ShapeSource>

        </MapboxGL.MapView>
      </View>
    )
  }
}
```

**Comment by digitaldavenyc** [comment] 2018-02-24 05:53
We are experiencing the same crash, it is happening almost every load. I've tried many of the suggestions from this thread and none have resolved it.

+1

**Comment by nitaliano** [comment] 2018-02-26 18:50
Let's track remote image crashes in this ticket

**Comment by atarsha** [comment] 2018-02-26 23:43
An example project that reproduces the crash:

https://github.com/atarsha/mapboxSymbolCrash

Everything of value is in App.js -- simply add your access token, run it from xCode, and toggle the switch back and forth until it crashes. You may see a couple different types of crashes. I am experiencing more than one crash and I think they're all related, as I haven't reproduced either when commenting out the SymbolLayer code.

**Closed as completed** 2018-03-01 16:47 UTC

**Comment by dorthwein** [comment] 2018-07-12 13:57
We're running into .png on the map crashing after 5 ish minutes of use on Android.  I know not very helpful.  Still trying to track down root cause/get a meaningful stack trace etc...  App will spike to 300 - 600mb memory with map open.
