### ISSUE TITLE
Android  annotationImage doesn't work 

### ISSUE THREAD

**Issue by KevinHu2014** [nitaliano/react-native-mapbox-gl#388] opened 2016-07-26 13:07 UTC
It seem that annotationImage doesn't work on Android.
By changing the image uri, it still display the same default red marker.

**Comment by dapetcu21** [comment] 2016-07-26 13:22
`annotationImage` does indeed not work yet on Android if you use remote images. Have you tried with local images?

**Comment by KevinHu2014** [comment] 2016-07-26 14:27
@dapetcu21 
Thanks for the fast reply.
I'm not sure what's the correct format ?
`annotationImage: {
        source: { require('./Img/item.png') },
        height: 25,
        width: 25
      },`

**Comment by KevinHu2014** [comment] 2016-07-26 14:54
After taking a brief look at `RNMGLAnnotationOptionsFactory.java` .
I'm still confuse with the format of using local images

**Comment by dapetcu21** [comment] 2016-07-27 09:35
It's

``` js
annotationImage: {
  source: { uri: 'item' }
  height: 25,
  width: 25
}
```

Then, as the [docs](https://github.com/mapbox/react-native-mapbox-gl/blob/master/API.md#annotations) state, you put your image in `android/app/src/main/res/drawable/item.png`

**Comment by KevinHu2014** [comment] 2016-07-27 10:30
@dapetcu21 
By trying the reply above .
There has the same problem displaying the same default red marker even by using local image.

**Comment by dapetcu21** [comment] 2016-07-27 10:33
I have confirmed `annotationImage` to be working on both Android and iOS with local images. I'm actually using it in a production app. You must be doing something wrong. Check that you're using `source: { uri: 'item' }`, check that the image is in `drawable` at that exact location, check that the `uri` does not contain the `.png` extension.

**Comment by KevinHu2014** [comment] 2016-07-27 10:35
@dapetcu21 
Thanks for the guide.
It's working now.
By the way , thanks for you contribution on react-native-mapbox-gl.
It really helps a lot.

**Comment by dapetcu21** [comment] 2016-07-27 10:36
I'll close this and open a new issue about remote images on android

**Closed as completed by dapetcu21** 2016-07-27 10:36 UTC
Labels: bug, Android

**Comment by brookehurford** [comment] 2016-08-27 00:43
If the marker is in the drawable location, will it also work for iOS? I have it now working for Android with a local image - but now the iOS marker isn't showing up. I am assuming because the file is in an android folder.

Where should the local image be placed for iOS, so that I can use the syntax, and have it work for both devices?

```
annotationImage: {
  source: { uri: 'marker' },
  height: 25,
  width: 25
}
```
