### ISSUE TITLE
getting an old version when adding the module to a react-native project

### ISSUE THREAD

**Issue by HananeAlSamrout** [nitaliano/react-native-mapbox-gl#382] opened 2016-07-23 13:12 UTC
hello, didn't you  add the changes to the npm? because i am getting the old version of this module when executing 'npm i --save react-native-mapbox-gl'

**Comment by dapetcu21** [comment] 2016-07-23 13:14
No. Not yet. Use npm install --save mapbox/react-native-mapbox-gl in the meantime. Duplicate of #379

**Closed as completed by dapetcu21** 2016-07-23 13:14 UTC

**Comment by HananeAlSamrout** [comment] 2016-07-23 13:16
thank you !
