### ISSUE TITLE
[v6] Setting pitch *and* centerCoordinate fails

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#723] opened 2017-11-09 14:28 UTC
If I use the following code, it will only set the center coordinate, but not also pitch the camera:
```
    this.mapbox.setCamera({
      centerCoordinate: someLngLatPosition,
      heading: 23,
      pitch: 60,
      zoom: 15,
      duration: 500
    });
```

Looking at the code, it appears it only applies one stop, rather than multiple, so I tried to be clever and do them sequentially like this:
```
    this.mapbox.setCamera({
      stops: [{
        heading: 23,
        pitch: 60,
        zoom: 15,
        duration: 500
      }, { centerCoordinate: someLngLatPosition, duration: 200 }]
    });
```
But that only sets the pitch, not the center coord. And if you swap the stops around, it only sets the center coord and not the pitch...

**Comment by nitaliano** [comment] 2017-12-21 01:04
@jliebrand this is fixed in `6.0.2`

```
 this.mapbox.setCamera({
      centerCoordinate: someLngLatPosition,
      heading: 23,
      pitch: 60,
      zoom: 15,
      duration: 500
 });
```

should work now, stops as well if you want to do them one at a time.

**Comment by jliebrand** [comment] 2017-12-21 08:50
Awesome! I'll give it a go (although likely after xmas now ;-))

**Comment by lilykaiser** [comment] 2018-01-21 22:33
Can this be closed?

**Comment by kristfal** [comment] 2019-03-18 19:59
Closing as the issue is resolved.

**Closed as completed by kristfal** 2019-03-18 19:59 UTC
