### ISSUE TITLE
[v6] - very first pinch zoom always uses centre of map as as zoom center

### ISSUE THREAD

**Issue by jliebrand** [nitaliano/react-native-mapbox-gl#680] opened 2017-10-20 13:22 UTC
(tested on iPad pro)

If you use the pinch gesture to zoom in/out as the very first thing after launching the app, it will always zoom in/out around the centre of the map, not the point between your fingers.

Once you drag the map once, after that the pinch zoom correctly zooms in/out around the point between your two fingers

**Comment by nitaliano** [comment] 2017-10-20 15:22
I will find out what the expected behavior should be with the camera. I believe this is happening because the camera is centered on the `centerCoordinate` that we set and all zooming will focus on that until a pan happens

**Comment by nitaliano** [comment] 2017-11-14 18:40
I'm closing this out, this is how the native camera behaves when setting the `centerCoordinate` I don't believe there is anything we can do in this repo to change it.

**Closed as completed by nitaliano** 2017-11-14 18:40 UTC
