### ISSUE TITLE
Android app is not responding  when reopen  after killing app 

### ISSUE THREAD

**Issue by phongnt57** [nitaliano/react-native-mapbox-gl#1023] opened 2018-02-05 10:42 UTC
When I start a new scene using router flux from map box screen and kill app by right button (recenly app button) then reopen app again, blank screen appear and show message "app is not responding".  I remove the mapbox component and problem disappear so i think problem is from mapbox memory leak. How can i complete kill app process and mapbox to solve this problem?

**Comment by nlindroos** [comment] 2018-02-05 12:58
Likely a duplicate of #878. You could post the relevant Logcat logs if your issue is different.

**Comment by nitaliano** [comment] 2018-02-13 21:56
Yes, this is a dupe of https://github.com/mapbox/react-native-mapbox-gl/issues/878 going to close out. @phongnt57 what version of the repo are you using btw?

**Closed as completed by nitaliano** 2018-02-13 21:56 UTC
