### ISSUE TITLE
loading style failed: HTTP status code 401

### ISSUE THREAD

**Issue by outdoorra** [nitaliano/react-native-mapbox-gl#917] opened 2017-12-29 19:03 UTC
Hi,

whenever I start the app for the first time the map view stays blank
and the error "[ERROR] {}[Setup]: loading style failed: HTTP status code 401" is showing up
in the logging window. After a "cmd+d  Reload" the map shows up fine.

Is this related to the issue of missing network connection? 
The Error is not really verbose. I also got another error in advance
"HTTP load failed (error code: -999 [1:89])"

[Black Screen after loading map Offline first time](https://github.com/mapbox/mapbox-gl-native/issues/3789)

**Comment by nitaliano** [comment] 2018-01-03 22:41
I haven't been able to reproduce this locally, but a 401 means unauthorized maybe it has something to do with your access token? Mind posting where you are setting your access token and rendering the map, they could be caught in a race condition

**Comment by outdoorra** [comment] 2018-01-03 23:15
I got a rootContainer right after Entry Point.
In the ComponentDidMount i am setting the token:

```
  async componentDidMount () {
    // if redux persist is not active fire startup action
    if (!ReduxPersist.active) {
      this.props.startup()
    }
    if (Config.IS_ANDROID) {
      const isGranted = await MapboxGL.requestAndroidLocationPermissions();
      this.setState({
        isAndroidPermissionGranted: isGranted,
        isFetchingAndroidPermission: false,
      })
    }
    MapboxGL.setAccessToken(Secrets.MAPBOX_API_KEY);
  }

```

**Comment by nitaliano** [comment] 2018-01-03 23:18
@outdoorra mind trying to set `MapboxGL.setAccessToken(Secrets.MAPBOX_API_KEY);` outside of your react component?

**Comment by outdoorra** [comment] 2018-01-03 23:38
I can't reproduce the error anymore. 
Sitting currently at the Starbucks and wonder if it might be related to
bad network at the last workplace. Surprising though, considering that 
this was an issue every single time for a week. I'll see if it happens again
and if so try to set the AccessToken outside of the component.

**Comment by nitaliano** [comment] 2018-01-03 23:49
cool, I'm going to close this out feel free to reopen if it happens again

**Closed as completed by nitaliano** 2018-01-03 23:49 UTC

**Comment by fabLamotte** [comment] 2021-10-08 09:07
Hello guys !

I faced this issue and resolved it by a clear cache.

I think that the app needed authorization for location that he didn't have.

It re-ask me authorization and it works fine.

**Comment by yonasKu** [comment] 2023-04-11 09:21
Mapbox error {com.project}[Setup]: loading style failed: HTTP status code 401 {"level": "error", "message": "{com.project}[Setup]: loading style failed: HTTP status code 401", "tag": "Mbgl"}
how can i fix this error

**Comment by chi-yeung** [comment] 2023-05-02 13:38
First time use of Mapbox-sdk-android produce similar error.
E/Mapbox: [maps-core]: {ps.testapp.auto}[Setup]: Failed to load style: HTTP status code 401
E/Mapbox: [maps-android\Mbgl-StyleObserver]: OnMapLoadError: STYLE, message: Failed to load style: HTTP status code 401, sourceID: null, tileID: null

The same Mapbox tokens are used for a different project with mapbox on the web.
Any suggestion for debugging this error ?

**Comment by chi-yeung** [comment] 2023-05-02 19:03
Article: "Troubleshoot styles" is helpful for verifying credentials/tokens.
https://docs.mapbox.com/help/troubleshooting/blank-tiles/

**Comment by Tordx** [comment] 2023-09-05 21:01
Turns out, it's a network issue.
