### ISSUE TITLE
[v6] SymbolLayer text style issues

### ISSUE THREAD

**Issue by kristfal** [nitaliano/react-native-mapbox-gl#709] opened 2017-11-03 12:46 UTC
Hey,

A couple of issues with text in `SymbolLayer`:

1) `textTranslate` crashes on iOS when assigning an array or camera function with stops.
2) `textAnchor` is missing valid anchor values in `StyleSheet`
3) `textTransform` is missing valid transform values in `StyleSheet`
4) `textJustify` is missing valid justify values in `StyleSheet`

**textTranslate**
The following style declarations crashes on iOS:

```js
textTranslate: [10, 10] ,

...

textTranslate: MapboxGL.StyleSheet.camera(
  {
    12: [8, 6],
    17: [17, 13],
  },
    MapboxGL.InterpolationMode.Exponential,
),
``` 

I haven't dug that deep into the issue, but propTypes seem to validate against the following shape that also seem to crash:

```js
PropTypes.shape({
  x: PropTypes.number.isRequired,
  y: PropTypes.number.isRequired,
});
```
Just a heads up, the [style spec](https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-symbol-text-translate) uses an array of numbers, not an object with keys to define text translation.

**Missing enums**
Following the standards of other style enums, I'd assume we'd define `textAnchor` as the following:
`textAnchor: MapboxGL.StyleSheet.TextAnchor.Right`, but currently `StyleSheet.TextAnchor` is `undefined`. The same goes for `textTransform` and `textJustify`.

**Comment by nitaliano** [comment] 2017-11-03 21:14
@kristfal the enum values are under `MapboxGL` so for example `MapboxGL.TextAnchor.Right`. You can see all the constants that are exported up here https://github.com/mapbox/react-native-mapbox-gl/blob/v6/ios/RCTMGL/MGLModule.m#L28. I'm going to take a look the textTranslate crash.

Update:
I see what the problem is this happened with `iconOffset` and `textOffset`, where I'm passing in an `NSArray` when it's expecting a `CGVector` just need to add this to prop to the `iosOverrides` map in the autogen script and that will fix this issue.

**Comment by nitaliano** [comment] 2017-11-03 22:03
I have this working locally, now as for the definition of translations in this SDK do people have any strong opions on `translate: {x : number, y: number}` vs `translate: [number, number]`?

**Comment by henrikra** [comment] 2017-11-04 17:05
First option 👍

**Comment by nitaliano** [comment] 2017-11-06 21:37
@kristfal the fix for `textTranslate` is in this PR https://github.com/mapbox/react-native-mapbox-gl/pull/705. The enums values are under `MapboxGL` instead of `MapboxGL.StyleSheet` and I think we're going to keep the translate definition as `{ x: number, y: number }`. Going to close this out, feel free to reopen or continue discussions in here.

**Closed as completed by nitaliano** 2017-11-06 21:37 UTC

**Comment by karlguillotte** [comment] 2018-01-11 16:46
Hi @nitaliano ,

I am still having an issue with the `textJustify` styling property. 

Thanks!
