### ISSUE TITLE
Installing via Cocoapods doesn't link the framework properly

### ISSUE THREAD

**Issue by joemckie** [nitaliano/react-native-mapbox-gl#417] opened 2016-09-20 16:09 UTC
When installing via Cocoapods, I still had to follow the manual installation and link the headers / framework to the project.

Was I installing it wrong, or is this a bug? I'll try on a fresh installation ASAP.

**Comment by joemckie** [comment] 2016-09-22 22:25
I got some time to take a look into whether this applies to a fresh installation, and it does. I get the following error on build:

```
Undefined symbols for architecture x86_64:
  "_convertToMGLAnnotation", referenced from:
      ___65-[RCTMapboxGLManager spliceAnnotations:deleteAll:toDelete:toAdd:]_block_invoke in libRCTMapboxGL.a(RCTMapboxGLManager.o)
  "_imageFromSource", referenced from:
      -[RCTMapboxGL mapView:imageForAnnotation:] in libRCTMapboxGL.a(RCTMapboxGL.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Setup

• Node: 6.5.0
• Ruby ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by 1ec5** [comment] 2016-09-27 18:18
Duplicate of #350.

**Closed as completed by 1ec5** 2016-09-27 18:18 UTC
Labels: ios

**Comment by joemckie** [comment] 2016-09-29 10:51
So is there a solution? Or is installing via CocoaPods broken?

**Comment by vjpr** [comment] 2016-10-29 14:40
@joemckie: I have the exact same error (except for architecture arm64) - how did you fix?

**Comment by brianjd** [comment] 2016-11-16 05:29
@1ec5 How is this a duplicate of #350?

**Comment by vjpr** [comment] 2016-11-16 15:30
@brianjd I think this is the fix: https://github.com/mapbox/react-native-mapbox-gl/issues/350#issuecomment-257099878

**Comment by joemckie** [comment] 2016-11-16 15:32
@vjpr I didn't really fix it with CocoaPods, I just followed the manual installation instructions instead

**Comment by brianjd** [comment] 2016-11-16 16:48
I ended up going the manual route as well.
