### ISSUE TITLE
Android Crash when switching connection 

### ISSUE THREAD

**Issue by fab1an** [nitaliano/react-native-mapbox-gl#460] opened 2016-11-21 10:04 UTC
MapboxGL crashes when switching network connection.

This pull requests fixes it: https://github.com/mapbox/mapbox-gl-native/pull/6858

Could this be integrated in react-native-mapbox-gl? Right now the bug is a showstopper for production :(. Thank you.

**Comment by fab1an** [comment] 2016-12-09 09:13
Any news on this?

**Comment by emmajam** [comment] 2016-12-20 05:29
@fab1an has this been fixed? My app also crashes when I change the connection

`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 bqHint=4 (has extras) } in com.mapbox.mapboxsdk.maps.MapView$ConnectivityReceiver@2a778c7`

`                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.setReachability(boolean)' on a null object reference`

from my Android monitor crash logs in Android studio

**Comment by fab1an** [comment] 2016-12-20 09:24
No, it doesn't appear to be fixed.

**Comment by fab1an** [comment] 2016-12-30 09:42
I added a pull-request for the sdk update which fixes this crash: https://github.com/mapbox/react-native-mapbox-gl/pull/481

**Comment by langsmith** [comment] 2017-04-03 17:47
Closing this because the discussion has moved over to #481

**Closed as completed by langsmith** 2017-04-03 17:47 UTC
