### ISSUE TITLE
CocoaPods Install Failure - framework not found Mapbox

### ISSUE THREAD

**Issue by digitaldavenyc** [nitaliano/react-native-mapbox-gl#402] opened 2016-08-15 18:34 UTC
I've been trying to setup react-native-mapbox-gl using cocoapods and receiving the following error: 

```
ld: framework not found Mapbox
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

my podfile:

```
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'discovery'
workspace 'discovery'

target 'swifter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for swifter
  pod 'React', :path => '../node_modules/react-native'
  pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
  pod 'React/RCTImage', :path => '../node_modules/react-native'
  pod 'React/RCTNetwork', :path => '../node_modules/react-native'
  pod 'React/RCTText', :path => '../node_modules/react-native'
  pod 'React/RCTWebSocket', :path => '../node_modules/react-native'

  pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'

  target 'discoveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

I've followed the instructions for manually installing as well and saw there is an open issue for that  too.

**Comment by quadsurf** [comment] 2016-09-14 23:20
Same issue for me... how is that your installer package is missing the framework file?

**Comment by quadsurf** [comment] 2016-09-14 23:40
@digitaldavenyc you know it's been a month since you asked this question, so i'm a bit shocked that mapbox hasn't responded to you yet... by any chance, have you found a workaround or solved this yet?

**Comment by quadsurf** [comment] 2016-09-14 23:45
[Issue #350](https://github.com/mapbox/react-native-mapbox-gl/issues/350) looks like it may help

**Comment by digitaldavenyc** [comment] 2016-09-15 16:22
@quadsurf I fixed this issue by including `node_modules/react-native-mapbox-gl/ios` in my search paths in XCode

**Comment by 1ec5** [comment] 2016-09-27 18:18
Duplicate of #350.

**Closed as completed by 1ec5** 2016-09-27 18:18 UTC
Labels: ios
