### ISSUE TITLE
MapboxGL.UserTrackingModes.FollowWithHeading How is the expression on android and ios different?

### ISSUE THREAD

**Issue by giantss** [nitaliano/react-native-mapbox-gl#1408] opened 2018-10-24 12:26 UTC
MapboxGL.UserTrackingModes.FollowWithHeading How is the expression on android and ios different? If you want to make the android expression consistent with ios, what do you need to do?

Rotating the phone horizontally on ios looks like this:
![auto](https://user-images.githubusercontent.com/13778798/47477917-1b364d80-d85a-11e8-8e60-63eacd5941f0.gif)

But on android, it does not achieve the expected results.

**Comment by giantss** [comment] 2018-10-25 05:42
@nitaliano Can you take the time to answer my questions, thank you.

**Comment by giantss** [comment] 2018-11-15 06:50
@nitaliano hey, How to solve this problem? This problem has been bothering me.

**Comment by kristfal** [comment] 2019-03-18 22:28
Hey,

the current approach will not allow us to solve this properly. We'll need to control this from RN side to achieve cross-platform parity. This ticket is a duplicate of a few others, so I'll close it and track the issue from a summary ticket.

**Closed as completed by kristfal** 2019-03-18 22:28 UTC

**Comment by hampelm** [comment] 2019-06-11 19:02
@kristfal, is #1461 the canonical issue for this, or is there a different one?
