### ISSUE TITLE
Flickering street names and disappearing FollowWithCourse marker

### ISSUE THREAD

**Issue by ferdicus** [nitaliano/react-native-mapbox-gl#884] opened 2017-12-15 09:49 UTC
OS: `OSX 10.12.6`
Platform: `Android 7`
RN: `0.50.3`
mapbox-gl: `6.0.2-rc1`

---------------------------

Hey there,
I've noticed, that there is a flickering of the street names and an concessional disappearance of the `FollowWithCourse` marker.

Please see attached gif:
![map](https://user-images.githubusercontent.com/26439946/34036018-326a2f12-e184-11e7-9026-f6d2c701a4c8.gif)

Explanation of what you're looking at:
* Recorded a route via `Lockito` (Android mock location app).
* Painted the route via ShapeSource and LineLayer Components
* set the `userTrackingMode` to `Mapbox.UserTrackingModes.FollowWithCourse`
* playing exported `Lockito` gpx in Android Emulator while observing the map.

I thought it is related to the emulator , however I also observed the same behavior when walking around having the same `userTrackingMode` and looking at the map.

I've attached the gpx file and my code for your consideration below.

It should be noted, that the street names/ marker do not flicker/ disappear when the map is panned by hand.

Thanks in advance

------------------------

```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@mapbox/react-native-mapbox-gl';

Mapbox.setAccessToken('<API-KEY>');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

const shape = {
  type: 'Feature',
  properties: {},
  geometry: {
    type: 'LineString',
    coordinates: [
      [8.67266, 50.11792],
      [8.67267, 50.11778],
      [8.673, 50.11673],
      [8.673, 50.11673],
      [8.67195, 50.11675],
      [8.67195, 50.11675],
      [8.67185, 50.11674],
      [8.67172, 50.11674],
      [8.67137, 50.11673],
      [8.6713, 50.11673],
      [8.67123, 50.11672],
      [8.67107, 50.11668],
      [8.67104, 50.11666],
      [8.67102, 50.11665],
      [8.67098, 50.11662],
      [8.67098, 50.11655],
      [8.67098, 50.11648],
      [8.67092, 50.11591],
      [8.67086, 50.11542],
      [8.67086, 50.11542],
      [8.6708, 50.11528],
      [8.67076, 50.11518],
      [8.67068, 50.11502],
      [8.67048, 50.11473],
      [8.67042, 50.11466],
      [8.67034, 50.11459],
      [8.67026, 50.11451],
      [8.67021, 50.11447],
      [8.66997, 50.11427],
      [8.6699, 50.11422],
      [8.66969, 50.11407],
      [8.66958, 50.11399],
      [8.66947, 50.11391],
      [8.66878, 50.11341],
      [8.66851, 50.11324],
      [8.66851, 50.11324],
      [8.66859, 50.11319],
      [8.66866, 50.11312],
      [8.66876, 50.11296],
      [8.6689, 50.11278],
      [8.66903, 50.11259],
      [8.66906, 50.11255],
      [8.6691, 50.11251],
      [8.66938, 50.11224],
      [8.66972, 50.11186],
      [8.66976, 50.11172],
      [8.67047, 50.11092],
      [8.67081, 50.11053],
      [8.67087, 50.11048],
      [8.67087, 50.11048],
      [8.67112, 50.11019],
      [8.67134, 50.10997],
      [8.67134, 50.10997],
      [8.66966, 50.1095]
    ]
  },
};

const layerStyles = {
  route: {
    lineColor: '#01c0ff',
    lineWidth: 5,
    lineOpacity: 0.3,
  },
};

class Map extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Mapbox.MapView
          styleURL={Mapbox.StyleURL.Street}
          ref={(ref) => { this.map = ref; }}
          zoomLevel={15}
          animated={true}
          attributionEnabled={false}
          showUserLocation={true}
          userTrackingMode={Mapbox.UserTrackingModes.FollowWithCourse}
          logoEnabled={false}
          style={styles.container}
        >
          <Mapbox.ShapeSource
            id='myRoute'
            shape={shape}
          >
            <Mapbox.LineLayer
              id='routeFill'
              style={layerStyles.route}
            />
          </Mapbox.ShapeSource>
        </Mapbox.MapView>
      </View>
    );
  }
}

export default Map;

```

GPX FILE: 
[map_bug.gpx.zip](https://github.com/mapbox/react-native-mapbox-gl/files/1562236/map_bug.gpx.zip)

**Comment by ferdicus** [comment] 2018-01-10 09:26
Hey there, hate to be that guy that bumps - but *bump* ? :)

**Comment by nitaliano** [comment] 2018-01-10 17:48
@ferdicus haha no shame in bumping

I'll look into this and see where the issue is happening. This might be a gl-native bug, if it is I'll post back here and we can open a ticket up in gl-native

thanks for reporting!

**Comment by ferdicus** [comment] 2018-01-11 11:15
Thanks @nitaliano 👍

**Comment by ferdicus** [comment] 2018-02-08 15:28
Hey @nitaliano any update on this?
Thanks.

**Comment by ferdicus** [comment] 2018-03-14 07:47
Sorry, me again... any update on this?

**Comment by nitaliano** [comment] 2018-03-15 19:32
Are you still running into this with `6.1.0`? It's running the latest Android SDK which might resolve your problem. I haven't run into this issue myself through testing.

**Comment by ferdicus** [comment] 2018-03-19 08:24
Hey there @nitaliano, I am now on `6.1.0-beta` and can confirm, that the flickering is gone, please see attached gif:

![mapbox](https://user-images.githubusercontent.com/26439946/37584783-238e6478-2b57-11e8-999d-49bbc1aca5fc.gif)

Although the flickering is gone and the map does _NOT_ pane smoothly the transition animation for the icon seems to be missing now. 
Did the api change? Am I missing some option?

Thanks

**Comment by kristfal** [comment] 2019-03-18 20:15
Hey,

in an effort to clean out old tickets, I'm closing this one. I'd recommend you try updating to the master branch to see if that fixes your problem. If not, please reopen the ticket.

**Closed as completed by kristfal** 2019-03-18 20:15 UTC
