### ISSUE TITLE
How to stop refreshing user location after first centering the map?

### ISSUE THREAD

**Issue by nbastoWM** [nitaliano/react-native-mapbox-gl#222] opened 2016-01-05 18:10 UTC
On `onRegionChange` I add an annotation for the current location.
I use `userTrackingMode={this.userTrackingMode.follow}` but in Android the annotation is always changing in very small steps and I can't pan the map because it recenters immediately. In iOS it's fine, it centers the map where you are, in the beginning, but then I can pan and zoom. 
If i set userTrackingMode to `none` I cannot center the map in my current location.
How can I center the map in my location only in the beginning but then allow the user to move the map?

**Comment by tobrun** [comment] 2016-01-06 07:12
@nbastoWM 
thank you for reaching out and flagging this issue,
I have created a ticket for this in the upstream repo https://github.com/mapbox/mapbox-gl-native/issues/3444.

**Comment by tobrun** [comment] 2016-01-19 13:32
This will land if update to android `3.0.1` in #249 lands.

**Comment by thibthibaut** [comment] 2016-01-20 10:33
The problem is that the behavior of onRegionChange is not the same on Android and iOS. If you look at the doc, you'll see:
iOS : Fired when the map **ends** panning or zooming
Android : Fired when the map **is** panning or zooming
This is a problem because if you wanna use the same code for Android and iOS you have different behaviors.

**Comment by nbastoWM** [comment] 2016-01-20 13:40
It would be great if we could get the user location when the map launches to set the `centerCoordinate`, and set the `userTrackingMode` to `none`.

But there's currently some bug with the `navigator.geolocation.getCurrentPosition` and I don't find any method in mapbox to get the current location.

**Comment by dapetcu21** [comment] 2016-07-23 08:39
3.0.1 landed a long time ago and this has been fixed since. 

Also, since 5.0.0, `userTrackingMode` now acts as any controlled component would: You set it to `follow` and when the user starts panning, you receive `onChangeUserTrackingMode` and set it back to `none` (or whatever the callback gives you).

Closing this.

**Closed as completed by dapetcu21** 2016-07-23 08:39 UTC
Labels: upstream, Android
