### ISSUE TITLE
[Android - Oreo] Map doesn't render when navigating to the page.

### ISSUE THREAD

**Issue by georific** [nitaliano/react-native-mapbox-gl#955] opened 2018-01-15 16:08 UTC
I am using using react-navigation to navigate to a page that contains a Mapbox.MapView.  The map doesn't render.  This only seems to be an issue when a device is running Oreo.  I have tried it on the Emulator as well as physical devices. Works fine if running device/emulator on API 25, 24...

Native stacktrace is below.

```
java.lang.IllegalStateException: setRenderer has already been called for this instance.
at android.opengl.GLSurfaceView.checkRenderThreadState(GLSurfaceView.java:1893)
at android.opengl.GLSurfaceView.setEGLContextClientVersion(GLSurfaceView.java:473)
at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.<init>(GLSurfaceViewMapRenderer.java:27)
at com.mapbox.mapboxsdk.maps.MapView$6.<init>(MapView.java:318)
at com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface(MapView.java:318)
at com.mapbox.mapboxsdk.maps.MapView.access$100(MapView.java:70)
at com.mapbox.mapboxsdk.maps.MapView$1.onGlobalLayout(MapView.java:143)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2238)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

I've tried to run `@mapbox/react-native-mapbox-gl` locally and point to the latest android aar `com.mapbox.mapboxsdk:mapbox-android-sdk:6.0.0-SNAPSHOT@aar` same error.

**App.js**
```
import React from 'react';
import { View, Text, Button, StyleSheet } from 'react-native';
import { StackNavigator } from 'react-navigation';
import MapboxMap from './Map';

const HomeScreen = ({ navigation }) => (
  <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
    <Text>Home Screen</Text>
    <Button
      onPress={() => navigation.navigate('MapPage')}
      title="Go to map"
    />
  </View>
);

const RootNavigator = StackNavigator({
  Home: {
    screen: HomeScreen,
  },
  MapPage: {
    screen: MapboxMap,
  },
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
export default RootNavigator;
```

**Map.js**
```
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@mapbox/react-native-mapbox-gl';

Mapbox.setAccessToken('pk.eyJ1IjoiNXhsIiwiYSI6ImNqOXdia2xjZDF1aGIydnBvc3oyaDduemcifQ.RtHbVUIOb-M02BVPDecV6Q');

export default class Map extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Mapbox.MapView
            styleURL={Mapbox.StyleURL.Street}
            zoomLevel={15}
            centerCoordinate={[11.256, 43.770]}
            style={styles.container}>
        </Mapbox.MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

```
**Platform: Android Oreo** (API 26)
**react-native-mapbox-gl:** v6.0.2

The test project can be found here to reproduce issue
https://github.com/georific/RNMapboxtest

### Steps to trigger behavior

 1. Launch Test app
 2. Click on button to go to map
 3. Map is blank, (native logs will show above stack trace) if not cmd + m to reload page, app will crash

### Expected behavior
Map should show on page

### Actual behavior
Blank map

**Comment by nitaliano** [comment] 2018-01-15 18:28
@georific thanks for the repo! I'll look into it

**Comment by georific** [comment] 2018-01-15 18:30
awesome thanks!

**Comment by nitaliano** [comment] 2018-01-16 19:29
@georific just wanted to comment back here I can reproduce the issue with your test repo. I cannot reproduce the issue with the example application(without react-navigation), could be something weird between react-navigation and this repo. I'll debug further and let you know what I find

**Comment by georific** [comment] 2018-01-16 19:41
@nitaliano there very well could be an issue with react-navigation and the way it navigates to the page however it seems to work with android API 25.  I have been digging around and it seems like the `mapbox-gl-native-android` is at api 25.  I am trying to see if I can get `mapbox-gl-native-android` building locally using compile and target SDK version 26

https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/gradle/dependencies.gradle#L3-L4

Thanks for looking into the issue.

**Comment by nitaliano** [comment] 2018-01-16 19:45
@georific If I move the Map view into the HomeScreen and don't navigate I see the map. I'm testing on an API 26 emulator

**Comment by georific** [comment] 2018-01-16 19:47
@nitaliano  yep, I didn't mention that but yes.  I will try another navigation component and see if that helps.

**Comment by frankrowe** [comment] 2018-01-16 21:22
same issue here, but if you rotate the phone to landscape, the map appears. it may have something to do with the map not rendering until `onLayout` of the containing view is called.

**Comment by nitaliano** [comment] 2018-01-16 21:28
I'm wondering if the View is initially being rendered without a width and height causing it to appear blank, because when you look at the inspector the Map view is not even on the screen, which makes me think it's under the top nav bar without a width and height

**Comment by nitaliano** [comment] 2018-01-16 22:16
`onMapReady` is not being called in the native code, I debugged it into there we enter the Mapbox Android SDK and that's it we never get the callback that the map is ready. Once we rotate our phone  that callback fires.

Update:
When I call `getParent()` in the native code(inside `RCTMGLMapView.java`) it's not attached to the view tree yet, causing `onMapReady` to never be called. Once the phone is rotated it does have a parent and `onMapReady` is called immediately.

**Comment by georific** [comment] 2018-01-16 23:06
interesting, ok, something specific to API 26 I guess?

**Comment by nitaliano** [comment] 2018-01-16 23:08
In the Mapbox Android SDK `MapView.java` there is a private method called `initialise` inside of that method it calls `getViewTreeObserver().addOnGlobalLayoutListener` and `onGlobalLayout` should be called next, but for some reason that is never called and we never even hit the code to initialize the GL surface

Here is a link to the code https://github.com/mapbox/mapbox-gl-native/blob/3c99bfdd1d610875daaa3aae884e86a9fc606443/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java#L135

@georific yes I can only make it happen on API 26

**Comment by nitaliano** [comment] 2018-01-16 23:18
I got it to appear on API 26 by forcing a global layout `getViewTreeObserver().dispatchOnGlobalLayout();`

**Comment by nitaliano** [comment] 2018-01-16 23:45
@georific here is a PR if you wanted to test it out https://github.com/mapbox/react-native-mapbox-gl/pull/960

**Comment by georific** [comment] 2018-01-17 00:16
@nitaliano awesome! I will test it out

**Comment by georific** [comment] 2018-01-17 02:43
@nitaliano it works great, nice work!  Thanks so much for your attention to this matter!

**Comment by nitaliano** [comment] 2018-01-17 18:10
@georific great I'll merge it in today and it will be part of our next npm publish

**Closed as completed** 2018-01-17 19:18 UTC
