### ISSUE TITLE
Crash when removing downloading offline pack

### ISSUE THREAD

**Issue by vanmik** [nitaliano/react-native-mapbox-gl#632] opened 2017-09-14 15:32 UTC
This report based on `example.js` file. 

First of all, in example code `Create offline pack` button doesn't do anything for two reasons:

1. It doesn't call `Mapbox.initializeOfflinePacks()` before calling `Mapbox.addOfflinePack()`
2. `bounds`, `minZoomLevel` and `maxZoomLevel` in config are invalid:

Here's the code:

```
        <Text onPress={() => {
            Mapbox.addOfflinePack({
              name: 'test',
              type: 'bbox',
              bounds: [0, 0, 0, 0],
              minZoomLevel: 0,
              maxZoomLevel: 0,
              metadata: { anyValue: 'you wish' },
              styleURL: Mapbox.mapStyles.dark
            }).then(() => {
              console.log('Offline pack added');
            }).catch(err => {
              console.log(err);
            });
        }}>
          Create offline pack
        </Text>
```

To reproduce crash below, you should fix those things. For example, like this:

```
        <Text onPress={() => {
            Mapbox.initializeOfflinePacks().then(() => {
              Mapbox.addOfflinePack({
                name: 'test',
                type: 'bbox',
                bounds: [42.00273287349021, 12.635713745117073, 41.74068098333959, 12.153523284912126],
                minZoomLevel: 4,
                maxZoomLevel: 15,
                metadata: { anyValue: 'you wish' },
                styleURL: Mapbox.mapStyles.dark
              }).then(() => {
                console.log('Offline pack added');
              }).catch(err => {
                console.log(err);
              });
            })
        }}>
          Create offline pack
        </Text>
```

Now to the actual bug.

**Steps to trigger behavior:**
1. Run `example.js` with build configuration `release`
2. Click "Create offline pack"
3. Wait a little bit while pack is downloading
4. Click "Remove pack with name 'test'"

**Expected behavior**
Pack should be removed

**Actual behavior**
Crash

Screencast with a crash: https://vanmik.ru/mapbox/crash.mov

Please test on a real device, not simulator, with build configuration `release` (it's important since crash does not happen every time for me in `debug` mode for some reason)

**Comment by nitaliano** [comment] 2017-09-14 16:24
I'll check it out

**Comment by nitaliano** [comment] 2017-09-21 17:12
@vanmik I tested `@mapbox/react-native-mapbox-gl@5.2.3-alpha1` and could not reproduce the crash with the example you provided. Would you mind trying that version out and letting me know how it goes? There was also a namespace change to the npm package so check this out https://github.com/mapbox/react-native-mapbox-gl/issues/634#issuecomment-330305488

**Comment by vanmik** [comment] 2017-09-25 13:59
@nitaliano I've tried the latest version (`@mapbox/react-native-mapbox-gl@5.2.3-alpha1`) but unfortunately the problem is still there. 

This crash is hard to reproduce since it does not happen every time for some reason. So I wrote a simple test which continuously repeats following steps:

1. call `addOfflinePack`
2. wait 5 seconds
3. call `removePack`
4. wait 5 seconds

Paste this code to `example.js`:

```
const delay = timeout => new Promise(resolve => setTimeout(resolve, timeout))

const addPack = () => Mapbox.addOfflinePack({
  name: 'test',
  type: 'bbox',
  bounds: [42.00273287349021, 12.635713745117073, 41.74068098333959, 12.153523284912126],
  minZoomLevel: 4,
  maxZoomLevel: 15,
  metadata: {anyValue: 'you wish'},
  styleURL: Mapbox.mapStyles.dark,
})

const removePack = () => Mapbox.removeOfflinePack('test')

const mapCrashTest = (times) => {
  console.log('add pack #' + times)
  return addPack()
    .then(() => delay(5000))
    .then(() => {
      console.log('remove pack #' + times)
      return removePack()
    })
    .then(() => delay(5000))
    .then(() => {
      if (times === 0) {
        return
      } 
      else {
        return mapCrashTest(times - 1)
      }
    })
}
```

and then trigger it somewhere in `MapExample` component, for example:

```
componentDidMount() {
  setTimeout(() => {
     Mapbox.initializeOfflinePacks().then(() => {
         mapCrashTest(100).then(() => alert('test has been successfully ended'))
     })
  }, 5000)
}
```

At some point the app will crash.

Please run this example with `release` build configuration.

Hope this would help to reproduce the crash. We are stuck with this problem for more than 3 weeks and cannot introduce offline functionality (number one feature request) for our users

**Comment by vanmik** [comment] 2017-10-06 13:05
Is there any news on that issue? If you still can’t reproduce the bug, we can provide more information.

**Comment by nitaliano** [comment] 2017-10-06 20:57
We are about 3-4 weeks away from releasing `v6` and it being merged into master. As with everything else in `v6` we are writing offline support from scratch.

Best case scenario for `v5` offline support is a branch that drops the offline module in, but it will not be merged into `v5`. We want to move away from the experimental code that's in `v5` as soon as possible.

**Comment by RobertSasak** [comment] 2017-10-07 21:01
@vanmik I have just updated to *5.2.3-alpha1*. I copied your mapCrashTest function into my existing app. I run 100 tests multiple times without any crash so far. 
There are few differences such as as I used custom raster tiles, small area about 4MB, real iPhone 7 device.

**Comment by nitaliano** [comment] 2017-11-07 00:31
Closing this out as we just merged in our `v6` rewrite. If this exists in the new version feel free to reopen.

**Closed as completed by nitaliano** 2017-11-07 00:31 UTC
