### ISSUE TITLE
[ANDROID]   v"6.0.2" map white

### ISSUE THREAD

**Issue by GuillotJessica** [nitaliano/react-native-mapbox-gl#957] opened 2018-01-16 09:38 UTC
the map seamed to render for a nano second and then all white, logos were at their on place, map came back with textureMode turned to false

**Comment by nitaliano** [comment] 2018-01-18 22:42
I can't reproduce this issue is there any other information you can provide?

**Comment by josenaves** [comment] 2018-02-13 13:01
This is also happening with me - I'm using 6.0.3-RC. This happens on the master branch version too.

In my case, I've tested it on Android emulator. I need to check on a real device.

**Comment by GuillotJessica** [comment] 2018-02-13 13:36
@josenaves give a try turning textureMode off

**Comment by josenaves** [comment] 2018-02-13 16:06
@GuillotJessica I've just set textMode={ false }
I still having a white map on emulator :(

**Comment by josenaves** [comment] 2018-02-13 17:15
GuillotJessica I tested it on a real tablet too (LGV520 - Android 7). This time, I can see the whole map, but the app is freezing. I'm trying to figure it out what is happening.

**Comment by nitaliano** [comment] 2018-02-14 00:58
@josenaves I was able to reproduce it on the emulator with API 24, but not API 26 as for it freezing this PR will help fix the ANR https://github.com/mapbox/react-native-mapbox-gl/pull/1033

**Comment by nitaliano** [comment] 2018-02-14 00:58
@GuillotJessica is this only happening to you in an emulator?

**Comment by GuillotJessica** [comment] 2018-02-14 08:17
I fixed it a while ago now, I suggest you turn to false all the props of the map and back to true one after the other, and see. Is the logo visible ?

**Comment by nitaliano** [comment] 2018-02-16 21:18
I'm going to close this out since it's emulator related there's not much we can do here expect be on the newer emulators

**Closed as completed by nitaliano** 2018-02-16 21:18 UTC
