### ISSUE TITLE
Android Callouts?

### ISSUE THREAD

**Issue by jayfunk** [nitaliano/react-native-mapbox-gl#293] opened 2016-02-27 03:13 UTC
Does Android support clicking on an annotation and getting a callout? I was under the impression that was not the case. I have been working with version 3.2.3 and there are weird cases where a callout will appear when click on an annotation point. The callout has the title text but is not rendered at the correct coordinates of the annotation.

![screen shot 2016-02-26 at 10 12 23 pm](https://cloud.githubusercontent.com/assets/2545666/13370477/1eedf590-dcd6-11e5-9412-640c208e1110.png)

**Comment by dapetcu21** [comment] 2016-07-23 08:24
Duplicate of #102. Also fixed in #365.

**Closed as completed by dapetcu21** 2016-07-23 08:24 UTC
