### ISSUE TITLE
Running application "main" with appParams

### ISSUE THREAD

**Issue by naveed89** [nitaliano/react-native-mapbox-gl#912] opened 2017-12-27 21:16 UTC
unning application "main" with appParams: {"initialProps":{"exp":{"initialUri":"exp://192.168.1.33:19000","manifest":{"isVerified":true,"version":"1.0.0","loading":{"iconUrl":"http://192.168.1.33:19001/assets/./assets/icons/loading-icon.png","icon":"./assets/icons/loading-icon.png"},"slug":"my-new-project","name":"my-new-project","iconUrl":"http://192.168.1.33:19001/assets/./assets/icons/app-icon.png","developer":{"tool":"xde","projectRoot":"E:\\MCS\\React Native\\Projects\\my-new-project"},"xde":true,"sdkVersion":"21.0.0","id":"@aziz89/my-new-project","mainModuleName":"node_modules/expo/AppEntry","packagerOpts":{"lanType":"ip","dev":true,"urlType":"exp","hostType":"lan","strict":false,"minify":false,"urlRandomness":"34-wwe"},"ios":{"supportsTablet":true},"bundleUrl":"http://192.168.1.33:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=E:\\MCS\\React Native\\Projects\\my-new-project\\node_modules\\expo\\tools\\hashAssetFiles","description":"An empty new project","orientation":"portrait","primaryColor":"#cccccc","privacy":"public","logUrl":"http://192.168.1.33:19000/logs","icon":"./assets/icons/app-icon.png","env":{},"debuggerHost":"192.168.1.33:19001"},"shell":false}},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
![screenshot_1514409050](https://user-images.githubusercontent.com/33197194/34393526-f6febd08-eb74-11e7-92dd-79798b40eb68.png)

when reloading its showin white screen

Launching Dev Tools...
1:56:56 AM
Google Chrome exited with error: { Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: 
   [ '/c',
     'start',
     '/wait',
     'chrome',
     'http://localhost:19001/debugger-ui' ] }

please help me to resolved this issue because i'm new in this

**Comment by nitaliano** [comment] 2018-01-03 22:49
I'm going to close this, as this is more of an RN setup and not a bug in the repo.

Have you solved your issue? Will be happy to help you debug it.

**Closed as completed by nitaliano** 2018-01-03 22:49 UTC

**Comment by Hypothesis-github** [comment] 2019-01-07 20:10
This issue does exist as of now and it prevents the source code to be recompiled to the emulator. please help me overcome this issue.

**Comment by kmiller9393** [comment] 2019-04-10 01:36
> This issue does exist as of now and it prevents the source code to be recompiled to the emulator. please help me overcome this issue.

@Hypothesis-github did you ever find a solution to this issue? I just recently ran into it as well in my React Native app. Everything was working fine for a while, so pretty sure my setup was okay. I did initialize my application with Expo though.
