### ISSUE TITLE
requestAndroidLocationPermissions

### ISSUE THREAD

**Issue by GuillotJessica** [nitaliano/react-native-mapbox-gl#913] opened 2017-12-28 13:46 UTC
I call this method in my map component to check and eventually grant permission from my user tu use is geolocation.
Here is my AndroidManiefest.xml
```
    <uses-feature    android:name="android.hardware.location" android:required="false" />
    <uses-feature    android:name="android.hardware.location.network" android:required="false" />
    <uses-feature    android:name="android.hardware.location.gps" android:required="false" />
    <uses-permission android:name="android.permission.LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```
I may be wrong but when I check for 
`console.warn("granted" + PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION === PermissionsAndroid.RESULTS.GRANTED);`
It returns false likewise your method seams to : 
in javascript/index.js
```
 if (res[permission] === PermissionsAndroid.RESULTS.GRANTED) {
        return true;
      }
```

My emulator works fine but my release crashes at first load and then fine
I know it is from react native component but yet your method.
Should I use this method in the root container instead?

**Comment by nitaliano** [comment] 2018-01-03 22:47
I haven't been able to reproduce the crash would you be able to post some more code of where you're calling that method and rendering the map?

**Comment by GuillotJessica** [comment] 2018-01-04 08:54
here's my code
```
async componentWillMount () {
        if (IS_ANDROID) {
            const isGranted = await MapboxGL.requestAndroidLocationPermissions();
            this.setState({
                isAndroidPermissionGranted: isGranted,
                isFetchingAndroidPermission: false,
            });
            }
}
```

and then 
```
<MapboxGL.MapView
                    key = {"mapId"}
                    ref = {(ref) => this.map = ref}
                    textureMode = {true}
                    style = {{height: 200}}
                    zoomLevel = {this.state.zoom}
                    showUserLocation = {!(IS_ANDROID && !this.state.isAndroidPermissionGranted )}
                    userTrackingMode={MapboxGL.UserTrackingModes.Follow}
                    centerCoordinate = {SF_OFFICE_COORDINATE}
                    minimumZoomLevel = {geoViewport.bounds([-75.03, 35.25], 14, [600, 400])}
                    maximumZoomLevel = {15}
                    attributionEnabled={false}
                    logoEnabled={false}
                    debugActive
                >

                    {/* images={{ example: exampleIcon, assets: ['pin'] }}>*/}
                    {/*<MapboxGL.ShapeSource
                    id='symbolLocationSource'
                    shape={this.state.featureCollection}
                    cluster
                    clusterMaxZoomLevel={10}
                    images={{ example: '../Images/M2S/IconesMap/tourismeGoutte.png'}}
                    >
                        <MapboxGL.SymbolLayer
                            id='symbolLocationSymbols'
                            minZoomLevel={10}
                        >
                        </MapboxGL.SymbolLayer>
                    </MapboxGL.ShapeSource>*/}
                    {this.AnnotationList()}
                </MapboxGL.MapView>
```
My emulator is Nexus_5X_API_25, but problem also exist in Nexus_5X_API_23, and in release different versions

**Comment by GuillotJessica** [comment] 2018-01-05 07:45
Hello @nitaliano, thx you
Here's my code
```
async componentWillMount () {
        if (IS_ANDROID) {
            const isGranted = await MapboxGL.requestAndroidLocationPermissions();
            this.setState({
                isAndroidPermissionGranted: isGranted,
                isFetchingAndroidPermission: false,
            });
        }
        ...
}
```

```
<MapboxGL.MapView
                    key = {"mapId"}
                    ref = {(ref) => this.map = ref}
                    textureMode = {true}
                    style = {{height: 200}}
                    zoomLevel = {this.state.zoom}
                    showUserLocation = {!(IS_ANDROID && !this.state.isAndroidPermissionGranted )}
                    userTrackingMode={MapboxGL.UserTrackingModes.Follow}
                    centerCoordinate = {SF_OFFICE_COORDINATE}
                    minimumZoomLevel = {geoViewport.bounds([-75.03, 35.25], 14, [600, 400])}
                    maximumZoomLevel = {15}
                    attributionEnabled={false}
                    logoEnabled={false}
                    debugActive
                >
                ...
                </MapboxGL.MapView>
```
I've got a different issue using an emulator with api 25, it still bugs but ask for permissions first, maybe it is cause of the upgrade of permissions system from 32 and above?
I wonder if it should be ask in a root component instead of the map component?

**Comment by nitaliano** [comment] 2018-03-12 18:31
Going to close this out since we resolved this in the chat

**Closed as completed by nitaliano** 2018-03-12 18:31 UTC

**Comment by GuillotJessica** [comment] 2018-03-12 19:59
thx again
