### ISSUE TITLE
Native exception on calling `MapboxGL.offlineManager.getPacks()`

### ISSUE THREAD

**Issue by mlandauer** [nitaliano/react-native-mapbox-gl#735] opened 2017-11-10 22:29 UTC
In my application I'm calling
```
const packs = await MapboxGL.offlineManager.getPacks()
```
in a callback from `MapboxGL.MapView` `onDidFinishLoadingMap`. 

I get the exception:
"unrecognized selector sent to instance 0x60400286bd00' was thrown while invoking getPacks on target MGLOfflineModule"

And the stacktrace:
```
2017-11-11 09:03:52.066 [fatal][tid:com.facebook.react.MGLOfflineModuleQueue] Exception '-[__NSDictionaryI dataUsingEncoding:]: unrecognized selector sent to instance 0x60400286bd00' was thrown while invoking getPacks on target MGLOfflineModule with params (
    17994,
    17995
)
callstack: (
	0   CoreFoundation                      0x00000001112a31ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010fc06f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111323a34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001112260a8 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000111225a88 _CF_forwarding_prep_0 + 120
	5   ThatsCamping                        0x000000010da3a346 -[MGLOfflineModule _unarchiveMetadata:] + 182
	6   ThatsCamping                        0x000000010da3ada7 -[MGLOfflineModule _convertPackToDict:] + 1159
	7   ThatsCamping                        0x000000010da39272 -[MGLOfflineModule getPacks:rejecter:] + 626
	8   CoreFoundation                      0x000000011122749c __invoking___ + 140
	9   CoreFoundation                      0x0000000111227370 -[NSInvocation invoke] + 320
	10  CoreFoundation                      0x000000011123fd56 -[NSInvocation invokeWithTarget:] + 54
	11  ThatsCamping                        0x000000010db4784c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796
	12  ThatsCamping                        0x000000010dbde1c2 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786
	13  ThatsCamping                        0x000000010dbddcef _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
	14  ThatsCamping                        0x000000010dbddc69 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	15  libdispatch.dylib                   0x0000000115c2c3f7 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000115c2d43c _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000115c3595b _dispatch_queue_serial_drain + 1162
	18  libdispatch.dylib                   0x0000000115c362df _dispatch_queue_invoke + 336
	19  libdispatch.dylib                   0x0000000115c3207d _dispatch_queue_override_invoke + 733
	20  libdispatch.dylib                   0x0000000115c391f9 _dispatch_root_queue_drain + 772
	21  libdispatch.dylib                   0x0000000115c38e97 _dispatch_worker_thread3 + 132
	22  libsystem_pthread.dylib             0x00000001160f15a2 _pthread_wqthread + 1299
	23  libsystem_pthread.dylib             0x00000001160f107d start_wqthread + 13
)
```

**Comment by nitaliano** [comment] 2017-12-21 00:42
I haven't been able to reproduce this one yet. This snippet `[__NSDictionaryI dataUsingEncoding:]:` makes me think we got bad data into the database and we're failing to parse it correctly.

**Comment by RobertSasak** [comment] 2017-12-28 10:44
I am receiving the same error when I am trying to upgrade from version 5 to 6. I am working on iPhone where packs were created on version 5 and I am trying to read them on version 6.
I can only assume that the way how packs are internally stored has changed. 
Is there a way of upgrading without loosing all the previously downloaded packs?

**Comment by RobertSasak** [comment] 2017-12-30 08:49
I deleted completely app from my iPhone and install it again. *getPacks()* does not crash any more. This is a serious issue for all users that already have an app with version 5 and update app to version 6. Is there a way of updating storage of tiles from v5 to v6?

**Comment by nitaliano** [comment] 2018-01-04 21:38
I normally would be against supporting something from v5(unofficial codebase) to v6(official codebase) but this issue I can understand can be a huge pain and bad user experience for your application so we can look into making the changes needed to be able to upgrade from v5 to v6 without losing the tiles.
 
Would you be able to provide a code sample for how you're using the offline tiles with v5 so I can create a quick project?

**Comment by RobertSasak** [comment] 2018-01-05 00:13
I am glad that you find it important. As this is show stopper for me right now. I am more than happy to assist you. 

I am not sure what should code sample would you like. I am downloading offline packs as follows. I always create an unique name for new offline pack to avoid any name collision. I store actual name of the pack in metadata as well as all other parameters. Note it is not possible metadata in v6. 
```js
add(name, mapStyle, bounds, zoom, center) {
    const id = guid();
    const params = {
        id,
        type: 'bbox',
        bounds,
        minZoomLevel: 0,
        maxZoomLevel: depth,
        styleURL: StyleUrl.get(mapStyle),
        // custom
        name,
        zoom,
        center,
        mapStyle,
    }
    return MapboxGL.addOfflinePack({
        ...params,
        name: id,
        metadata: params,
    });
},
```

**Comment by nitaliano** [comment] 2018-01-05 00:19
@RobertSasak thanks that is what I was looking for code wise just wanted to make sure I'm setting the properties the same way

**Comment by RobertSasak** [comment] 2018-01-24 14:58
@nitaliano I have seen some changes in offline manager lately. Have you manage to address also upgrading issue from v5?

**Comment by RobertSasak** [comment] 2018-02-01 12:29
I have tested on latest *master* and the issue persists. I cannot locate in the Mapbox code where is the logic for storing offline packs. Any advice?

**Comment by nitaliano** [comment] 2018-02-01 13:14
It's happening in the c++ codebase under gl-native this repo only has control over method calls

**Comment by RobertSasak** [comment] 2018-02-01 18:43
Thank you for pointing me in the right direction. You are right, magic happens in *mapbox-gl-native* repo in *mapbox-gl-native/platform/default/mbgl/storage/offline_database.cpp*.
I looked into SQL database cache.db in v5 and v6. I don't see a big difference. So I gave up. And now I am looking at the * _unarchiveMetadata* in https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMGL/MGLOfflineModule.m#L272
It seems to me that error occurs when parsing JSON. Here is the picture of of content of *data* right before it crash.
![screen shot 2018-02-01 at 19 35 20](https://user-images.githubusercontent.com/281281/35696513-0705f0a2-0788-11e8-9038-c36057abaa77.png)
And here are *data* on v6.
![screen shot 2018-02-01 at 19 56 40](https://user-images.githubusercontent.com/281281/35697326-1fbece28-078a-11e8-9274-fff9e8f3a74a.png)

Clearly * _unarchiveMetadata* expects NString but get key/value pair. Where would be the best way to fix this?

**Comment by nitaliano** [comment] 2018-02-01 18:49
@RobertSasak I believe that since the underlying objects are different between v5/v6 that is why it's failing

This is the v5 object https://github.com/mapbox/react-native-mapbox-gl/blob/5.2.2/ios/RCTMapboxGL/RCTMapboxGLManager.m#L368

We'll most likely need a special case block when we unarchive on iOS to support the old versions of the pack.

Is this the error you are seeing being raised https://developer.apple.com/documentation/foundation/nsinvalidarchiveoperationexception?language=objc?

**Comment by RobertSasak** [comment] 2018-02-01 22:41
@nitaliano In the end I decided to return metadata without changes. *metadata* are nested inside metadata which differs from the format in v6. I found it easier to handle this backward compatibility in JS.

**Comment by nitaliano** [comment] 2018-02-02 19:59
Closing this out `getPacks` does not crash anymore for `v5` -> `v6` packs on master

**Closed as completed by nitaliano** 2018-02-02 19:59 UTC

**Comment by atarsha** [comment] 2018-02-02 21:35
@nitaliano should we leave this open to track the necessity to investigate/repair the issue for Android as well?

**Comment by nitaliano** [comment] 2018-02-03 00:22
I opened a new issue https://github.com/mapbox/react-native-mapbox-gl/issues/1021
