### ISSUE TITLE
Error when showing centerCoordinate

### ISSUE THREAD

**Issue by krvajal** [nitaliano/react-native-mapbox-gl#1032] opened 2018-02-12 18:04 UTC
I have a simple mapview component and it gets rendered properly, but if I add a centerCoordinate prop the following errors shows up

![image 2018-02-12 at 19 03 30](https://user-images.githubusercontent.com/5899385/36111736-6f0f9818-1027-11e8-949c-6485b44e2d55.png)

Any idea what is causing this?
# Source code

```
  <MapboxGL.MapView
        ref={c => (this._map = c)}
        zoomLevel={12}
        styleURL={MapboxGL.StyleURL.Street}
        centerCoordinate={[-122.452652, 37.762963]}
      />
      
```

**Comment by atarsha** [comment] 2018-02-12 18:05
Can you show the definition of DEFAULT_CENTER_COORDINATE? It should be an array: [long, lat]

**Comment by krvajal** [comment] 2018-02-12 18:08
Updated to show the actual value.

**Comment by atarsha** [comment] 2018-02-12 18:10
Without more code, it's difficult to troubleshoot. I can only speculate that DEFAULT_CENTER_COORDINATE isn't what you expect it to be, or one of the [onDidFinishLoadingMap, onRegionDidChange] functions contains something that is breaking. Try commenting those out.

**Comment by krvajal** [comment] 2018-02-12 18:17
@atarsha I have updated the code to the minimum that can reproduce the error

**Comment by atarsha** [comment] 2018-02-12 18:25
Have you tried hardcoding in that default value instead of the define you originally posted? The minimal code you posted works fine.

**Comment by krvajal** [comment] 2018-02-12 18:28
@atarsha yes I tried hardcoing and it does not work for me. I am running it just the way shown above and it gives me that error

**Comment by nitaliano** [comment] 2018-02-12 18:32
`_helpers2.default.point` is coming from turf helpers can you try a clean npm install?

**Comment by krvajal** [comment] 2018-02-12 18:33
I tracked down the error and it is coming from this call here `https://github.com/mapbox/react-native-mapbox-gl/blob/master/javascript/utils/geoUtils.js#L4`

**Comment by nitaliano** [comment] 2018-02-12 23:52
Have you tried to `rm -rf node_modules && npm i`? It's saying it can't find the turf helpers module https://github.com/mapbox/react-native-mapbox-gl/blob/master/package.json#L42

**Comment by nitaliano** [comment] 2018-02-13 21:55
I'm going to close this out since it seems that others are not having this problem and I cannot reproduce the issue. You can comment back in here and I can help you

**Closed as completed by nitaliano** 2018-02-13 21:55 UTC
